name = just_coords
title = Just Coords
author = jcorri
supported_games = *
description = A configurable HUD that displays the player's position, direction, and biome in multiple modes, colors, sizes, and positions.
